[project]
name = 'backend'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bitcoin-call]
path = 'contracts/bitcoin-call.clar'
clarity_version = 2
epoch = 2.1

[contracts.sbtc]
path = 'contracts/sbtc.clar'
clarity_version = 2
epoch = 2.1

[contracts.sip009-nft-trait]
path = 'contracts/sip009-nft-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.sip010-ft-trait]
path = 'contracts/sip010-ft-trait.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
